[package]
name = "volo-rate-limiter"
version = "0.1.0"
edition = "2021"

[features]
tokio = ["dep:futures", "dep:tokio"]

[dependencies]
volo = "*"
futures = { version = "0.3", optional = true }
tokio = { version = "1", features = ["time", "sync"], optional = true }
